// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crcowjetzgmznuxtikxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyY293amV0emdtem51eHRpa3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjg4MzIsImV4cCI6MjA2MTg0NDgzMn0.tzQxAP1nD_ZomFnjbr9yu3mt9Oc_SxkfMGgGtZ1YJu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);